FORMAT: 1A

# EJBCA REST API

Endpoints to perform user and certificate management

# Group EJBCA system administration

## EJBCA version [/ejbca/version]

### get EJBCA version [GET]

Get EJBCA version

+ Response 200 (application/json)

          {
            "version": "EJBCA 6.3.1.1 Community (r21429)"
          }

# Group EJBCA CA management

## Certification authorities management [/ca]

### List all avaliable CAs [GET]

+ Response 200 (application/json)

        {
          "CAs": [
              {
                  "id": 576968287,
                  "name": "IOTmidCA"
              },
              {
                  "id": -1371917878,
                  "name": "PROTOCOL"
              }
          ]
        }

## Get CA certificate [/ca/{cacn}]

### Give the PEM certificate chain of the given CA [GET]

The returned certificate is a base64 string with newline characters (so that it
can match PEM format).

To save the chain in a .CRT file, add the first and last line as shown below:
```
-----BEGIN CERTIFICATE-----
[Certificate]
-----END CERTIFICATE----- 
```

Be careful to properly copy the first and final line: the number of dashes (-)
must be exactly as shown above.

To view the contents of this certificate, execute the following command: 

```bash
openssl x509 -in ./Certificate.crt.pem -text -noout
```

+ Response 400 (application/json)

        {
            "status": 400,
            "message": "soap message: CA with name abcde does not exist."
        }

+ Response 200 (application/json)

        {
            "certificate": "*base64cert chain with linebreaks"
        }



## Certificate status [/ca/{cacn}/certificate/{certserial}/status]
### Check if a certificate is revoked [GET]
If the certificate serial number does not exist EJBCA will return 'not revoked'.
This endpoint is not working well.
+ Parameters
  + cacn: IOTmidCA (required, string): Certificate name
  + certserial: 5017406860984553086 (required, string): certificate serial number




+ Response 400 (application/json)

        {
          "status": 400,
          "message": "soap message: Could not find CA with name null and ID 1992101327"
        }
        
+ Response 200 (application/json)

        {
          "status": {
              "date": "2017-08-21T17:26:03.322000+00:00",
              "reason": "CERTIFICATEHOLD"
          }
        }

+ Response 200 (application/json)

        {
          "status": {
              "date": "1969-12-31T23:59:59.999000+00:00",
              "reason": "NOTREVOKED"
          }
        }

## Certificate [/ca/{cacn}/certificate/{certserial}]
### Get the base64 pem certificate [GET]
+ Response 400 (application/json)

        {
          "status": 400,
          "message": "soap message: Could not find CA with name null and ID 1992101327"
        }

+ Response 200 (application/json)

        {
          "certificate": {
              "certificate": null,
              "keyStore": null,
              "type": 0,
              "certificateData": "MIICozCCAYugAwIBAgIIDbsv7z5yer..."
          }
        }

### Revoke a certificate [DELETE /ca/{cacn}/certificate/{certserial}?{reason}]
Removes a user certificate
+ Parameters
  + reason: UNSPECIFIED (optional, enum) - one of REVOKATION_REASON enum values. default: UNSPECIFIED

+ Response 400 (application/json)

        {
          "status": 400,
          "message": "soap message: Could not find end entity certificate. Issuer CN=PROTOCOL, serialNo 4690394092950658023."
        }

+ Response 400 (application/json)
  
        {
          "status": 400,
          "message": "soap message: Certificate is already revoked. Issuer: 'CN=PROTOCOL', serno: 5084496247959973."
        }

+ Response 200 (application/json)
  
        {
          "status": 200,
          "message": "ok"
        }

## CRL [/ca/{caname}/crl]
### Create or update current CRL [PUT]
+ Response 400 (application/json)

        {
          "status": 400,
          "message": "soap message: CA with name caname does not exist."
        }

+ Response 200 (application/json)

        {
          "status": 200,
          "message": "ok"
        }

### get a CRL [GET /ca/{caname}/crl?{delta}]
Use the command 

.. code-block:: bash
  openssl asn1parse -inform DER -in crl.der - dump 
  
to visualize the CRL

+ Parameters
  + delta: false (optional, boolean) - if a elta CRL should be used. default: false

+ Response 400 (application/json)

        {
          "status": 400,
          "message": "soap message: CA with name caname does not exist."
        }

+ Response 200 (application/json)

        {
          "CRL": "MIICQjCCASoCAQEwDQYJKoZIhvcNAQEFBQAwEzERMA8GA1UEAwwIUF..."
        }

# Group EJBCA user management
## Create or edit user [/user]
### Create or edit a user [POST]

+ Request (application/json)
  + Body

            {
                "caName": "PROTOCOL",
                "certificateProfileName": "ENDUSER",
                "clearPwd": true,
                "email": "device21@noemail.com",
                "endEntityProfileName" : "EMPTY",
                "extendedInformation": {
                            "name": "somekey",
                            "value": "somevalue"
                        },
                "keyRecoverable": true,
                "password": "pwd12",
                "sendNotification": false,
                "status": 10,
                "subjectDN": "CN=device21",
                "tokenType": "USERGENERATED",
                "username" : "device21"
            }

+ Response 200 (application/json)

        {
          "status": 200,
          "message": "ok"
        }

## User CRUD [/user/{username}]
### get user data [GET]
notice that the repsonse is a list
+ Response 200 (application/json)

        {
          "user": [
              {
                  "caName": "PROTOCOL",
                  "cardNumber": null,
                  "certificateProfileName": "ENDUSER",
                  "certificateSerialNumber": null,
                  "clearPwd": false,
                  "email": "device21@noemail.com",
                  "endEntityProfileName": "EMPTY",
                  "endTime": null,
                  "extendedInformation": [
                      {
                          "name": "subjectdirattributes",
                          "value": null
                      },
                      {
                          "name": "somekey",
                          "value": "somevalue"
                      }
                  ],
                  "hardTokenIssuerName": null,
                  "keyRecoverable": false,
                  "password": null,
                  "sendNotification": false,
                  "startTime": null,
                  "status": 40,
                  "subjectAltName": null,
                  "subjectDN": "CN=device21",
                  "tokenType": "USERGENERATED",
                  "username": "device21"
              }
          ]
        }


### Revoke all cerificates from a user [DELETE /user/{username}?{reason,delete}]
+ Parameters
  + reason: UNSPECIFIED (optional, enum) - one of REVOKATION_REASON enum values. default: UNSPECIFIED
  + delete: false (optional, boolean) - True if the user should be deleted after the revocation. Default False

+ Response 200 (application/json)

        {
          "status": 200,
          "message": "ok"
        }


## List user valid certificates [/user/{username}/find]
### List user certs [GET /user/{username}/find?{valid}]
+ Parameters
  + valid: true (optional, boolean) - False if revoked certificates should be listed. Default True

+ Response 404 (application/json)

        {
          "status": 404,
          "message": "no certificates found"
        }

+ Response 200 (application/json)

        {
          "certs": [
              {
                  "certificate": null,
                  "keyStore": null,
                  "type": 0,
                  "certificateData": "MIICozCCAYugAwIBAgIIDbsv7z5yerMwDQ..."
              }
          ]
        }

## Sign a certificate for a user [/user/{username}/pkcs10]
### Return the signed certificate [POST]

+ Request (application/json)
  In a csv file, generated with the command 'openssl req -new -out server.csr -key server.key'
  The base64 certificate csv is between the tags '-----BEGIN CERTIFICATE REQUEST-----' and '-----END CERTIFICATE REQUEST-----'

  + Body

            {
              "passwd": "pwd12",
              "certificate": "MIIBmzCCAQQCAQAwWzELMAkGA1UEBhMCQlIxEzARBgNVMC..."
            }

+ Response 404 (application/json)

        {
          "status": 400,
          "message": "soap message: Got request with status GENERATED (40), NEW, FAILED or INPROCESS required: username."
        }

+ Response 200 (application/json)

        Add a '-----BEGIN PKCS7-----' and '-----END PKCS7-----' before save the given certificate to a file.  

        {
          "status": {
              "data": "MIAGCSqGSIb3DQEHAqCAMIACAQExCzAJBgUrDgMCGg...",
              "responseType": "PKCS7"
          }
        }
